squoosh-cli --resize '{"enabled":true,"width":5120,"height":5120,"method":"lanczos3","fitMethod":"contain","premultiply":true,"linearRGB":true}' --webp '{"quality":50,"target_size":0,"target_PSNR":0,"method":5,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' $1 -d ./static -s -desktop-2x

squoosh-cli --resize '{"enabled":true,"width":2560,"height":2560,"method":"lanczos3","fitMethod":"contain","premultiply":true,"linearRGB":true}' --webp '{"quality":50,"target_size":0,"target_PSNR":0,"method":5,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' $1 -d ./static -s -desktop-1x

squoosh-cli --resize '{"enabled":true,"width":4676,"height":4676,"method":"lanczos3","fitMethod":"contain","premultiply":true,"linearRGB":true}' --webp '{"quality":50,"target_size":0,"target_PSNR":0,"method":5,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' $1 -d ./static -s -tablet-2x

squoosh-cli --resize '{"enabled":true,"width":2338,"height":2338,"method":"lanczos3","fitMethod":"contain","premultiply":true,"linearRGB":true}' --webp '{"quality":50,"target_size":0,"target_PSNR":0,"method":5,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' $1 -d ./static -s -tablet-1x

squoosh-cli --resize '{"enabled":true,"width":2502,"height":2502,"method":"lanczos3","fitMethod":"contain","premultiply":true,"linearRGB":true}' --webp '{"quality":50,"target_size":0,"target_PSNR":0,"method":5,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' $1 -d ./static -s -phone-3x

squoosh-cli --resize '{"enabled":true,"width":1668,"height":1668,"method":"lanczos3","fitMethod":"contain","premultiply":true,"linearRGB":true}' --webp '{"quality":50,"target_size":0,"target_PSNR":0,"method":5,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' $1 -d ./static -s -phone-2x

squoosh-cli --resize '{"enabled":true,"width":834,"height":834,"method":"lanczos3","fitMethod":"contain","premultiply":true,"linearRGB":true}' --webp '{"quality":50,"target_size":0,"target_PSNR":0,"method":5,"sns_strength":50,"filter_strength":60,"filter_sharpness":0,"filter_type":1,"partitions":0,"segments":4,"pass":1,"show_compressed":0,"preprocessing":0,"autofilter":0,"partition_limit":0,"alpha_compression":1,"alpha_filtering":1,"alpha_quality":100,"lossless":0,"exact":0,"image_hint":0,"emulate_jpeg_size":0,"thread_level":0,"low_memory":0,"near_lossless":100,"use_delta_palette":0,"use_sharp_yuv":0}' $1 -d ./static -s -phone-1x